language: node_js

node_js:
  - '12'

services:
  - docker

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  install:
    - echo ${SSH_KEY} | base64 -d >> $HOME/.ssh/known_hosts
  on:
    branch: cicd
