language: node_js

node_js:
  - '12'

services:
  - docker

install:
  - npm ci
  - echo ${SSH_KEY_BASE64} | base64 -d >> $HOME/.ssh/known_hosts

script:
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: cicd
