name: Build and deploy Tabutask frontend

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 95.163.213.142
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist,nginx.conf"
          target: "/home/ubuntu/Tabutask/Frontend"
